### ISSUE TITLE
Broken files in v1.6.0 Source archives (and in some previous releases)

### ISSUE THREAD

**Issue by d-ovs** [hifight/Footsies#2]
Project do not open correctly in desired unity version because of broken asset files.
The majority of the files has the same small size.
For example, Footsies/Assets/Sound/BGM/Footsies.wav in archive weights only about 1KB, but the same file in Master weights about 3.8MB.
The broken files contains something like that:
```
version https://git-lfs.github.com/spec/v1
oid sha256:fe99261edea28b548dcdfb83b0d9359e753c434bbb2f697cd183d004c7d6c242
size 57942
```
instead of actual data.
Maybe your unity Git tools wasn't correctly configured?

**Comment by hifight** [comment]
It's because of Git LFS settings. I disabled that and reupload those assets so that it doesn't use LFS anymore. Please try download .zip file again.

**Comment by d-ovs** [comment]
@hifight I see, but there are still broken files in zips in "Releases" tab. I just wanted to upload the latest sources with implemented GGPO.

**Comment by hifight** [comment]
Can you just download from Code tab? (clone or download). 

I don't have control over the released source file. Maybe if I draft a new release, the new source file will be corrected now but I don't want to just make a new release for that.

**Comment by d-ovs** [comment]
@hifight Ok. It seems to be working. Thank you for great project and for your help.
