### ISSUE TITLE
v1.6.0: Online not working.

### ISSUE THREAD

**Issue by wallstaples** [hifight/Footsies#3]
When I choose Online VS, the connection screen says "Error: UDP blocked. Cannot get public ip/port". Clicking Start Host and Join Host doesn't do anything. I have UPnP enabled on my router, so I don't know what the problem is.

**Comment by hifight** [comment]
It's nearly impossible to figure and fix this for me. That 1.6.0 was super early test and I don't have plan to update that anymore. I'm working on Steam version which is much more stable. If you're interested, dm me on twitter and I will send closed beta test to you.
